package Assignment2;

//There are 5 of each type
public enum ApparatusType {
	LEGPRESSMACHINE, BARBELL, HACKSQUATMACHINE, LEGEXTENSIONMACHINE, 
	LEGCURLMACHINE, LATPULLDOWNMACHINE, PECKDECKMACHINE,
	CABLECROSSOVER
}
